export * from './user/user.service'
export * from './auth/auth.service'
export * from './prisma/prisma.service'
export * from './logger/logger.service'
export * from './config/config.service'
// export * from './role/role.service'
export * from './customers/customers.service'
export * from './device/device.service'
export * from './payment/payment.service'
export * from './mail/mail.service'
export * from './prisma-mongo/prisma.service'